name: PyLint

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Code Review Scoring
        run: find . -name '*.py' -print -exec pylint {} \;
      - name: Analysing code with PyLint
        run: |
#          pylint $(find . -name '*.py') --fail-under=8.0
          pylint_score=$(pylint $(find . -name '*.py') --fail-under=8.0 --exit-zero --output-format=text | tee /dev/tty | grep 'Your code has been rated at' | sed 's/.*rated at \([-0-9.]*\)\/.*/\1/')
          echo "Pylint score: $pylint_score"
          # Assuming you have a script or service to generate/update the badge
          badge_url="https://img.shields.io/badge?score=$pylint_score"
          echo "Badge URL: $badge_url"
      - name: Update README with Pylint Badge
        run: python update_readme.py README.md ${{ env.NEW_BADGE_URL }}


